name: PR Workflow

on: [pull_request]

jobs:
  lint:
    uses: andyMrtnzP/browserless-test/.github/workflows/lint.yml@main

  automerge:
    needs: [lint]
    uses: andyMrtnzP/browserless-test/.github/workflows/merge-dependabot.yml@main
